-- Map original SVG demo media to Speaking Part 2/3 prompts. Paths are relative and subdirectory-safe in the frontend.
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image','assets/aptis/media/city-cafe.svg','People talking and working in a café.',10 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_2' AND MOD(CRC32(COALESCE(topic,'')),5)=0;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image','assets/aptis/media/quiet-library.svg','Students reading in a quiet library.',10 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_2' AND MOD(CRC32(COALESCE(topic,'')),5)=1;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image','assets/aptis/media/park-walk.svg','People walking and exercising in a park.',10 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_2' AND MOD(CRC32(COALESCE(topic,'')),5)=2;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image','assets/aptis/media/team-office.svg','Colleagues discussing work in an office.',10 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_2' AND MOD(CRC32(COALESCE(topic,'')),5)=3;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image','assets/aptis/media/train-station.svg','Travellers waiting at a train station.',10 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_2' AND MOD(CRC32(COALESCE(topic,'')),5)=4;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image_a','assets/aptis/media/online-study.svg','A learner studying online at home.',10 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_3' AND MOD(CRC32(COALESCE(topic,'')),4)=0;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image_b','assets/aptis/media/classroom-study.svg','Students studying together in a classroom.',20 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_3' AND MOD(CRC32(COALESCE(topic,'')),4)=0;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image_a','assets/aptis/media/busy-market.svg','A busy market with shoppers.',10 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_3' AND MOD(CRC32(COALESCE(topic,'')),4)=1;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image_b','assets/aptis/media/quiet-library.svg','A quiet library with readers.',20 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_3' AND MOD(CRC32(COALESCE(topic,'')),4)=1;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image_a','assets/aptis/media/team-office.svg','People working together in an office.',10 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_3' AND MOD(CRC32(COALESCE(topic,'')),4)=2;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image_b','assets/aptis/media/online-study.svg','A person working or studying from home.',20 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_3' AND MOD(CRC32(COALESCE(topic,'')),4)=2;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image_a','assets/aptis/media/park-walk.svg','People spending time in a city park.',10 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_3' AND MOD(CRC32(COALESCE(topic,'')),4)=3;
INSERT IGNORE INTO aptis_question_media(question_id,media_role,media_path,alt_text,sort_order) SELECT id,'image_b','assets/aptis/media/seaside-relax.svg','People relaxing near the sea.',20 FROM aptis_questions WHERE module='speaking' AND type='speaking_part_3' AND MOD(CRC32(COALESCE(topic,'')),4)=3;