-- Hotfix 020: restore 14 Aptis Writing tasks skipped by the (module,prompt(190)) unique-prefix key.
-- Cause: two groups in seed 013 contain eight long prompts whose first 190 characters are identical.
-- This seed rephrases the seven skipped variants in each group so their unique prefixes differ.
-- Safe for existing databases: INSERT IGNORE + content_seeds tracking makes the hotfix idempotent.

INSERT IGNORE INTO aptis_questions
(module,type,topic,difficulty,prompt,passage,options_json,correct_answer,explanation,audio_text,time_limit_seconds,source_note,is_active,created_by)
VALUES
('writing','writing_part_4','Library','B2','Think of a recent example. The library has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Refer to a recent example.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Library','B2','Focus on why this matters to you. The library has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Explain why it matters to you.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Library','B2','Describe one change you have noticed. The library has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Mention one change you have noticed.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Library','B2','Use one specific example. The library has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Include a specific example.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Library','B2','Explain how this affects your routine. The library has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Describe how it affects your routine.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Library','B2','Suggest one improvement you would like to see. The library has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Mention what you would like to improve.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Library','B2','Give a clear reason for your view. The library has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Give one reason for your view.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Environment Group','B2','Think of a recent example. The environment group has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Refer to a recent example.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Environment Group','B2','Focus on why this matters to you. The environment group has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Explain why it matters to you.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Environment Group','B2','Describe one change you have noticed. The environment group has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Mention one change you have noticed.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Environment Group','B2','Use one specific example. The environment group has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Include a specific example.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Environment Group','B2','Explain how this affects your routine. The environment group has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Describe how it affects your routine.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Environment Group','B2','Suggest one improvement you would like to see. The environment group has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Mention what you would like to improve.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL),
('writing','writing_part_4','Environment Group','B2','Give a clear reason for your view. The environment group has announced a change that may inconvenience members. Write an informal message to a friend and a formal email to the manager explaining your reaction and suggesting a practical solution. Give one reason for your view.',NULL,NULL,NULL,'Use the appropriate register and check task completion, grammar, vocabulary, organisation, coherence, and word count.',NULL,1200,'YangLingo Adaptive original practice content',1,NULL);
