<?php
/**
 * YangLingo runtime configuration.
 *
 * Production secrets belong in config.local.php (generated by setup.php) or
 * environment variables. Never commit a real config.local.php.
 */
$base = [
    'app_name' => 'YangLingo',
    'app_url' => getenv('APP_URL') ?: '',
    'timezone' => getenv('APP_TIMEZONE') ?: 'Asia/Ho_Chi_Minh',
    'debug' => filter_var(getenv('APP_DEBUG') ?: '0', FILTER_VALIDATE_BOOL),
    'db' => [
        'host' => getenv('DB_HOST') ?: '',
        'port' => (int)(getenv('DB_PORT') ?: 3306),
        'name' => getenv('DB_NAME') ?: '',
        'user' => getenv('DB_USER') ?: '',
        'pass' => getenv('DB_PASS') ?: '',
        'charset' => 'utf8mb4',
    ],
    'openrouter_api_key' => getenv('OPENROUTER_API_KEY') ?: '',
    'openrouter_model' => getenv('OPENROUTER_MODEL') ?: 'openrouter/free',
    'max_upload_bytes' => 10 * 1024 * 1024,
    'session_lifetime' => 7 * 24 * 60 * 60,
    'login_max_failures' => 5,
    'login_lock_minutes' => 15,
];

$local = __DIR__ . '/config.local.php';
if (is_file($local)) {
    $override = require $local;
    if (is_array($override)) {
        $base = array_replace_recursive($base, $override);
    }
}

return $base;
