<?php
declare(strict_types=1);

@ini_set('session.cookie_httponly', '1');
@ini_set('session.use_strict_mode', '1');
$https = (!empty($_SERVER['HTTPS']) && strtolower((string)$_SERVER['HTTPS']) !== 'off') || ((int)($_SERVER['SERVER_PORT'] ?? 0) === 443);
session_set_cookie_params(['path'=>'/','secure'=>$https,'httponly'=>true,'samesite'=>'Lax']);
session_start();

$root = __DIR__;
$lockFile = $root . '/storage/installed.lock';
$configFile = $root . '/config.local.php';
$installed = is_file($lockFile) && is_file($configFile);
$message = '';
$success = false;

if (empty($_SESSION['setup_csrf'])) $_SESSION['setup_csrf'] = bin2hex(random_bytes(32));

function h(string $v): string { return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function defaultAppUrl(bool $https): string {
    $host = trim((string)($_SERVER['HTTP_HOST'] ?? ''));
    return $host !== '' ? (($https ? 'https' : 'http') . '://' . $host) : '';
}

if (!$installed && ($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    try {
        if (!hash_equals((string)$_SESSION['setup_csrf'], (string)($_POST['csrf'] ?? ''))) {
            throw new RuntimeException('Phiên cài đặt đã hết hạn. Hãy tải lại trang.');
        }
        if (!class_exists('PDO') || !in_array('mysql', PDO::getAvailableDrivers(), true)) {
            throw new RuntimeException('Hosting chưa bật PDO MySQL (pdo_mysql).');
        }

        $dbCfg = [
            'host' => trim((string)($_POST['db_host'] ?? '')),
            'port' => max(1, (int)($_POST['db_port'] ?? 3306)),
            'name' => trim((string)($_POST['db_name'] ?? '')),
            'user' => trim((string)($_POST['db_user'] ?? '')),
            'pass' => (string)($_POST['db_pass'] ?? ''),
            'charset' => 'utf8mb4',
        ];
        if ($dbCfg['host'] === '' || $dbCfg['name'] === '' || $dbCfg['user'] === '') {
            throw new RuntimeException('Hãy nhập đầy đủ MySQL Host, Database và DB User do HelioHost cấp.');
        }
        if (!preg_match('/^[A-Za-z0-9_$.-]+$/', $dbCfg['name'])) {
            throw new RuntimeException('Tên database chứa ký tự không được hỗ trợ bởi trình cài đặt.');
        }

        $appUrl = rtrim(trim((string)($_POST['app_url'] ?? '')), '/');
        if ($appUrl === '' || !filter_var($appUrl, FILTER_VALIDATE_URL)) {
            throw new RuntimeException('APP URL không hợp lệ. Ví dụ: https://yourdomain.helioho.st');
        }
        $openrouter = trim((string)($_POST['openrouter_key'] ?? ''));
        $model = trim((string)($_POST['openrouter_model'] ?? 'openrouter/free')) ?: 'openrouter/free';

        // Connect directly to the database HelioHost already created. Some shared hosts
        // intentionally do not grant CREATE DATABASE, so setup never requires that privilege.
        $dsn = 'mysql:host=' . $dbCfg['host'] . ';port=' . $dbCfg['port'] . ';dbname=' . $dbCfg['name'] . ';charset=utf8mb4';
        $pdo = new PDO($dsn, $dbCfg['user'], $dbCfg['pass'], [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);
        $pdo = null;

        $local = [
            'app_url' => $appUrl,
            'db' => $dbCfg,
            'openrouter_api_key' => $openrouter,
            'openrouter_model' => $model,
            'debug' => false,
        ];
        $php = "<?php\n// Generated by setup.php. Do not commit this file.\nreturn " . var_export($local, true) . ";\n";
        if (file_put_contents($configFile, $php, LOCK_EX) === false) {
            throw new RuntimeException('Không ghi được config.local.php. Kiểm tra quyền ghi thư mục website.');
        }

        require_once $root . '/lib/Database.php';
        $db = new Database($dbCfg, $root . '/database/schema.sql', $root . '/database/migrations', $root . '/database/seeds');
        $db->ensureSchema();

        $adminEmail = strtolower(trim((string)($_POST['admin_email'] ?? '')));
        $adminName = trim((string)($_POST['admin_name'] ?? 'YangLingo Admin'));
        $adminPassword = (string)($_POST['admin_password'] ?? '');
        if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) {
            throw new RuntimeException('Email ADMIN không hợp lệ.');
        }
        if (mb_strlen($adminName) < 2 || mb_strlen($adminName) > 100) {
            throw new RuntimeException('Tên ADMIN phải từ 2 đến 100 ký tự.');
        }
        if (strlen($adminPassword) < 8) {
            throw new RuntimeException('Mật khẩu ADMIN phải có ít nhất 8 ký tự.');
        }
        $adminHash = password_hash($adminPassword, PASSWORD_DEFAULT);
        if ($adminHash === false) throw new RuntimeException('Không thể tạo password hash cho ADMIN.');
        $existing = $db->one('SELECT id FROM users WHERE email=?', [$adminEmail]);
        if ($existing) {
            $db->run("UPDATE users SET name=?,password_hash=?,role='admin',is_active=1 WHERE id=?", [$adminName,$adminHash,$existing['id']]);
        } else {
            $db->run("INSERT INTO users(name,email,password_hash,role,is_active) VALUES(?,?,?,'admin',1)", [$adminName,$adminEmail,$adminHash]);
        }
        $adminPassword = '';

        if (!is_dir($root . '/storage')) @mkdir($root . '/storage', 0755, true);
        if (file_put_contents($lockFile, "installed_at=" . date('c') . "\n", LOCK_EX) === false) {
            throw new RuntimeException('Cài đặt database xong nhưng không tạo được khóa setup. Hãy tạo storage/installed.lock hoặc đổi quyền ghi.');
        }
        @chmod($configFile, 0640);
        @chmod($lockFile, 0640);

        $success = true;
        $installed = true;
        $message = 'Cài đặt thành công. Database cũ (nếu có) được giữ nguyên; schema chỉ bổ sung phần còn thiếu.';
    } catch (Throwable $e) {
        $message = $e instanceof PDOException
            ? 'Không kết nối được MySQL. Hãy kiểm tra Host, Database, User và Password trong Plesk.'
            : $e->getMessage();
    }
}

$appDefault = defaultAppUrl($https);
?><!doctype html>
<html lang="vi">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>Thiết lập YangLingo trên HelioHost</title>
<style>
:root{color-scheme:dark;--bg:#07110f;--panel:#0d1916;--surface:#12211d;--line:#263b35;--text:#eef8f4;--muted:#9cb3aa;--primary:#78e3b6;--danger:#ff9a9a;--radius:20px}*{box-sizing:border-box}body{margin:0;font-family:Inter,"Be Vietnam Pro",system-ui,-apple-system,sans-serif;background:radial-gradient(circle at 20% 0,#123229 0,transparent 38%),var(--bg);color:var(--text);min-height:100vh}.wrap{width:min(920px,calc(100% - 32px));margin:48px auto}.brand{display:flex;align-items:center;gap:12px;margin-bottom:24px}.logo{width:44px;height:44px;border-radius:14px;background:var(--primary);color:#082017;display:grid;place-items:center;font-weight:900}.panel{border:1px solid var(--line);background:rgba(13,25,22,.96);border-radius:var(--radius);padding:30px;box-shadow:0 30px 80px rgba(0,0,0,.25)}h1{font-size:clamp(28px,5vw,46px);line-height:1.08;margin:0 0 10px}p{color:var(--muted);line-height:1.65}.notice{padding:14px 16px;border-radius:14px;background:var(--surface);border:1px solid var(--line);margin:18px 0}.ok{border-color:#3b9b78}.bad{border-color:#a24f4f;color:#ffdede}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:24px}.full{grid-column:1/-1}label{display:grid;gap:7px;font-weight:700;font-size:13px}label span{color:var(--muted);font-weight:500}input{width:100%;border:1px solid var(--line);background:#081410;color:var(--text);border-radius:12px;padding:13px 14px;outline:none}input:focus{border-color:var(--primary);box-shadow:0 0 0 3px rgba(120,227,182,.14)}button,.btn{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:12px;padding:13px 18px;font-weight:850;background:var(--primary);color:#072018;text-decoration:none;cursor:pointer}.hint{padding:14px;border:1px dashed var(--line);border-radius:14px;color:var(--muted);font-size:13px;line-height:1.6}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0}.step{background:var(--surface);border:1px solid var(--line);padding:14px;border-radius:14px}.step b{display:block;margin-bottom:4px}.step small{color:var(--muted)}code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;color:#c8ffe8}@media(max-width:720px){.wrap{margin:20px auto}.panel{padding:20px}.grid,.steps{grid-template-columns:1fr}.full{grid-column:auto}}
</style>
</head>
<body><main class="wrap">
<div class="brand"><div class="logo">YL</div><div><b>YangLingo</b><div style="color:var(--muted);font-size:13px">Production setup · HelioHost / PHP + MySQL</div></div></div>
<section class="panel">
<h1>Thiết lập production</h1>
<p>Điền đúng thông tin database trong Plesk. Trình cài đặt sẽ chạy schema theo kiểu không phá dữ liệu, tạo/nâng quyền tài khoản ADMIN và tự khóa sau khi hoàn tất.</p>
<div class="steps"><div class="step"><b>1 · MySQL</b><small>Dùng DB đã tạo trên HelioHost</small></div><div class="step"><b>2 · Schema</b><small>CREATE/ALTER, không DROP database</small></div><div class="step"><b>3 · Lock</b><small>Setup tự khóa sau thành công</small></div></div>
<?php if($message):?><div class="notice <?=$success?'ok':'bad'?>"><?=h($message)?></div><?php endif;?>
<?php if($installed):?>
<div class="notice ok"><b>YangLingo đã được cài đặt.</b><br><span style="color:var(--muted)">Nếu cần cấu hình lại, hãy xóa thủ công <code>storage/installed.lock</code> và kiểm tra <code>config.local.php</code> qua File Manager.</span></div>
<a class="btn" href="index.php">Mở YangLingo →</a>
<?php else:?>
<form method="post" autocomplete="off">
<input type="hidden" name="csrf" value="<?=h((string)$_SESSION['setup_csrf'])?>">
<div class="grid">
<label class="full">APP URL <span>Domain/subdomain production</span><input name="app_url" value="<?=h((string)($_POST['app_url']??$appDefault))?>" placeholder="https://yourname.helioho.st" required></label>
<label>MySQL Host <span>Lấy trong Plesk</span><input name="db_host" value="<?=h((string)($_POST['db_host']??''))?>" placeholder="MySQL host do HelioHost/Plesk cấp" required></label>
<label>MySQL Port <span>Thường là 3306</span><input name="db_port" inputmode="numeric" value="<?=h((string)($_POST['db_port']??'3306'))?>" required></label>
<label>Database <span>Tên database đã tạo</span><input name="db_name" value="<?=h((string)($_POST['db_name']??''))?>" required></label>
<label>DB User <span>User được gán vào database</span><input name="db_user" value="<?=h((string)($_POST['db_user']??''))?>" required></label>
<label class="full">DB Password <span>Chỉ được ghi vào config.local.php trên server</span><input type="password" name="db_pass" required></label>
<label class="full">OpenRouter API key <span>Tùy chọn; có thể để trống</span><input type="password" name="openrouter_key" placeholder="Không bắt buộc"></label>
<label class="full">OpenRouter model <span>Tùy chọn</span><input name="openrouter_model" value="<?=h((string)($_POST['openrouter_model']??'openrouter/free'))?>"></label>
<label>ADMIN Name <span>Tên hiển thị quản trị viên</span><input name="admin_name" value="<?=h((string)($_POST['admin_name']??'YangLingo Admin'))?>" minlength="2" maxlength="100" required></label>
<label>ADMIN Email <span>Tài khoản đăng nhập quản trị</span><input type="email" name="admin_email" value="<?=h((string)($_POST['admin_email']??''))?>" autocomplete="username" required></label>
<label class="full">ADMIN Password <span>Tối thiểu 8 ký tự; chỉ hash được lưu trong database</span><input type="password" name="admin_password" minlength="8" autocomplete="new-password" required></label>
<div class="full hint"><b>Bảo mật:</b> source không chứa email hoặc mật khẩu ADMIN cố định. Mật khẩu bạn nhập ở bước này được hash bằng <code>password_hash()</code> trước khi ghi database.</div>
<div class="full"><button type="submit">Cài đặt YangLingo</button></div>
</div>
</form>
<?php endif;?>
</section></main></body></html>
