<?php
declare(strict_types=1);
$root=dirname(__DIR__);
function readCsv(string $path):array{$h=fopen($path,'rb');if(!$h)throw new RuntimeException("Missing $path");$head=fgetcsv($h);$head[0]=preg_replace('/^\xEF\xBB\xBF/','',$head[0]);$rows=[];while(($r=fgetcsv($h))!==false){if(count($r)<count($head))$r=array_pad($r,count($head),'');$rows[]=array_combine($head,array_slice($r,0,count($head)));}fclose($h);return $rows;}
function failq(string $m):never{fwrite(STDERR,"FAIL: $m\n");exit(1);} 
$g=readCsv($root.'/database/seeds/adaptive_global_learning_1449.csv');$t=readCsv($root.'/database/seeds/toeic_adaptive_300.csv');$a=readCsv($root.'/database/seeds/aptis_adaptive_608.csv');$f=readCsv($root.'/database/seeds/aptis_fidelity_110.csv');$c12=readCsv($root.'/database/seeds/connected_speech_12.csv');$c82=readCsv($root.'/database/seeds/connected_speech_82.csv');
$types=[];$seen=[];foreach($g as $r){$types[$r['item_type']]=($types[$r['item_type']]??0)+1;$k=strtolower(trim($r['item_type'].'|'.$r['term']));if(isset($seen[$k]))failq("Duplicate learning item $k");$seen[$k]=1;if(trim($r['term'])===''||trim($r['meaning_vi'])==='')failq('Empty learning item');foreach(['lorem ipsum'] as $bad)if(str_contains(strtolower($r['example_en']??''),$bad))failq("Placeholder global item: $bad");}
$expected=['VOCABULARY'=>410,'COLLOCATION'=>260,'SENTENCE_PATTERN'=>193,'GRAMMAR_LESSON'=>53,'LISTENING_RECOGNITION'=>340,'PARAPHRASE'=>193];foreach($expected as $k=>$n)if(($types[$k]??0)!==$n)failq("$k expected $n got ".($types[$k]??0));
if(count($t)!==300)failq('TOEIC adaptive pack expected 300');$parts=[];$qseen=[];foreach($t as $r){$parts[$r['part']]=($parts[$r['part']]??0)+1;$q=trim($r['question']);if($q===''||isset($qseen[$q]))failq('Missing/duplicate TOEIC question');$qseen[$q]=1;if(!in_array($r['correct_option'],['A','B','C','D'],true))failq('Bad TOEIC correct option');$opt=$r['option_'.strtolower($r['correct_option'])];if(trim((string)$opt)!==trim((string)$r['correct_answer']))failq('TOEIC answer not aligned with option');if(trim($r['explanation'])==='')failq('TOEIC explanation missing');}
foreach(['2'=>70,'5'=>100,'6'=>50,'7'=>80] as $p=>$n)if(($parts[$p]??0)!==$n)failq("Part $p expected $n");
if(count($a)!==608)failq('Aptis baseline expected 608');$mods=[];$aseen=[];foreach($a as $r){$mods[$r['module']]=($mods[$r['module']]??0)+1;$k=$r['module'].'|'.trim($r['prompt']);if(trim($r['prompt'])===''||isset($aseen[$k]))failq('Missing/duplicate Aptis baseline prompt');$aseen[$k]=1;if(in_array($r['module'],['grammar','vocabulary','reading','listening'],true)&&trim((string)$r['correct_answer'])==='')failq('Missing Aptis answer');}
$want=['grammar'=>150,'vocabulary'=>150,'reading'=>90,'listening'=>90,'speaking'=>64,'writing'=>64];foreach($want as $m=>$n)if(($mods[$m]??0)!==$n)failq("$m expected $n");
if(count($f)!==110)failq('Aptis fidelity replacements expected 110');$fseen=[];$fd=[];foreach($f as $r){$k=$r['module'].'|'.$r['type'].'|'.trim($r['prompt']);if(isset($fseen[$k]))failq('Duplicate Aptis replacement');$fseen[$k]=1;$fd[$r['module'].'|'.$r['type']]=($fd[$r['module'].'|'.$r['type']]??0)+1;if(trim($r['explanation'])==='')failq('Replacement explanation missing');if($r['type']==='word_matching'){if(!is_array(json_decode($r['options_json'],true))||!is_array(json_decode($r['correct_answer'],true)))failq('Malformed word_matching JSON');}}
foreach(['vocabulary|word_matching'=>10,'vocabulary|word_combination'=>10,'vocabulary|meaning_in_context'=>10,'vocabulary|word_pairs'=>10,'reading|text_cohesion'=>20,'reading|long_text'=>20,'reading|opinion_matching'=>15,'reading|heading_matching'=>15] as $k=>$n)if(($fd[$k]??0)!==$n)failq("Fidelity distribution $k expected $n");
$fidelitySql=file_get_contents($root.'/database/seeds/016_aptis_task_fidelity.sql');if(substr_count($fidelitySql,'SET is_active=0')!==110)failq('Aptis retired count expected 110');if(str_contains(strtoupper($fidelitySql),'DELETE FROM APTIS_QUESTIONS'))failq('Aptis retirement must preserve history');
$allc=array_merge($c12,$c82);$keys=[];foreach($allc as $r){$k=strtolower(trim($r['formal_form']??$r['phrase']??''));if($k===''||isset($keys[$k]))failq('Duplicate/empty connected speech expansion');$keys[$k]=1;}if(count($c12)!==12||count($c82)!==82)failq('Connected-speech expansion counts differ');
$baseSql=file_get_contents($root.'/database/migrations/007_toeic_part1_7_starter_and_connected_speech.sql');$seg=explode('ON DUPLICATE KEY UPDATE',explode('INSERT INTO connected_speech_examples',$baseSql,2)[1],2)[0];preg_match_all('/^\(\'/m',$seg,$mm);$connectedTotal=count($mm[0])+count($c12)+count($c82);if($connectedTotal!==100)failq("Connected speech expected 100, got $connectedTotal");preg_match_all("/^\('(?:''|[^'])*','(?:''|[^'])*','(?:''|[^'])*','((?:''|[^'])*)'/m",$seg,$bm);$allPhraseKeys=array_map(fn($v)=>strtolower(str_replace("''","'",trim($v))),$bm[1]);foreach($c12 as $r)$allPhraseKeys[]=strtolower(trim($r['formal_form']));foreach($c82 as $r)$allPhraseKeys[]=strtolower(trim($r['phrase']));if(count($allPhraseKeys)!==count(array_unique($allPhraseKeys)))failq('Duplicate connected-speech formal phrase across base/seeds');
$cor=file_get_contents($root.'/database/seeds/018_content_quality_corrections.sql');preg_match_all('/^UPDATE global_learning_items/m',$cor,$cm);if(count($cm[0])!==459)failq('Content correction count expected 459');foreach(['Apply the rule','This sentence demonstrates','Check the sentence form','In this situation, the team needs to','The phrase “'] as $bad)if(str_contains($cor,$bad))failq("Generic grammar correction remains: $bad");
foreach(['lorem ipsum','test question','example test'] as $bad){$hay=strtolower(file_get_contents($root.'/database/seeds/011_global_learning_library.sql').file_get_contents($root.'/database/seeds/012_toeic_adaptive_expansion.sql').file_get_contents($root.'/database/seeds/013_aptis_adaptive_expansion.sql'));if(str_contains($hay,$bad))failq("Placeholder detected: $bad");}
echo "DATA QUALITY OK: global=".count($g).", TOEIC=".count($t).", Aptis_active=608, Aptis_retired=110, connected=100, corrected=459\n";
