'use strict';
// Actual practice and notebook modules; synthetic DOM, accounts, API and storage only.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const practice=fs.readFileSync(path.join(__dirname,'../assets/practice-lab.js'),'utf8');
const notebook=fs.readFileSync(path.join(__dirname,'../assets/learning-notebook.js'),'utf8');
const pronunciation=require('../assets/pronunciation.js');
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const decode=s=>s.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const clone=value=>JSON.parse(JSON.stringify(value));
let assertions=0,scenarios=0;
function check(value,message){assert.ok(value,message);assertions++;}
async function scenario(name,test){await test();scenarios++;console.log('PASS '+name);}
const cards=[
  {id:101,term:'follow up',definition:'liên hệ tiếp để hỏi tiến triển',example_en:'I will follow up tomorrow.',example_vi:'Tôi sẽ liên hệ tiếp vào ngày mai.',explanation:'Follow up on a request.',ipa:'',part_of_speech:'phrasal verb',card_type:'COLLOCATION'},
  {id:102,term:'awake',definition:'thức giấc',example_en:'I awoke early today.',example_vi:'Hôm nay tôi thức giấc sớm.',explanation:'Awoke là V2.',ipa:'US /əˈweɪk/',part_of_speech:'verb',card_type:'VOCABULARY'},
  {id:103,term:'unless',definition:'trừ khi',example_en:'I will walk unless it rains.',example_vi:'Tôi sẽ đi bộ trừ khi trời mưa.',explanation:'Unless + mệnh đề.',ipa:'',part_of_speech:'conjunction',card_type:'GRAMMAR'},
];
const savedSession=(overrides={})=>({setId:37,setTitle:'Synthetic book',lesson:{value:1,title:'Synthetic lesson'},cards:clone(cards),queue:cards.map((_,index)=>({index,mode:'recall',repeat:false})),pos:0,responses:cards.map(()=>null),retryResults:cards.map(()=>null),retryAdded:false,feedback:null,...overrides});
function environment({saved=null,sourceCards=cards,hash='#practice/37'}={}){
  let document;
  class Element{
    constructor(tag,attrs={}){this.tag=tag;this.attrs=attrs;this.children=[];this.parent=null;this._html='';this._text='';this.value=attrs.value||'';this.checked='checked'in attrs;this.disabled='disabled'in attrs;this.hidden='hidden'in attrs;this.isConnected=true;this.dataset={};for(const[k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;}
    descendants(){return this.children.flatMap(child=>[child,...child.descendants()]);}
    disconnect(){this.isConnected=false;this.children.forEach(child=>child.disconnect());}
    set innerHTML(value){this.children.forEach(child=>child.disconnect());this.children=[];this._text='';this._html=value;const stack=[this];
      for(const m of value.matchAll(/<\/?([a-z][\w-]*)\b([^>]*?)>|([^<]+)/gi)){
        if(m[3]){stack.at(-1)._text+=decode(m[3]);continue;}
        if(m[0][1]==='/'){while(stack.length>1&&stack.at(-1).tag!==m[1].toLowerCase())stack.pop();if(stack.length>1)stack.pop();continue;}
        const attrs={};for(const a of m[2].matchAll(/([\w-]+)(?:="([^"]*)")?/g))attrs[a[1]]=decode(a[2]||'');
        const child=new Element(m[1].toLowerCase(),attrs);child.parent=stack.at(-1);child.parent.children.push(child);if(!['input','br','hr','img','meta','link'].includes(child.tag))stack.push(child);
      }
      for(const n of this.descendants()){if(n.tag==='textarea')n.value=n.textContent;if(n.tag==='select'){const options=n.descendants().filter(c=>c.tag==='option');n.value=(options.find(c=>'selected'in c.attrs)||options[0])?.attrs.value||'';}}
    }
    get innerHTML(){return this._html;}
    get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}
    set textContent(value){this.children.forEach(c=>c.disconnect());this.children=[];this._text=String(value);this._html='';}
    setAttribute(key,value){this.attrs[key]=String(value);}
    getAttribute(key){return this.attrs[key]??null;}
    matches(selector){return selector.split(',').some(part=>{part=part.trim();const tag=part.match(/^[\w-]+/)?.[0];if(tag&&tag!==this.tag)return false;const id=part.match(/#([\w-]+)/)?.[1];if(id&&this.attrs.id!==id)return false;for(const a of part.matchAll(/\[([\w-]+)(?:="([^"]*)")?\]/g))if(!(a[1]in this.attrs)||a[2]!==undefined&&this.attrs[a[1]]!==a[2])return false;return true;});}
    querySelector(selector){return this.descendants().find(n=>n.matches(selector))||null;}
    querySelectorAll(selector){return this.descendants().filter(n=>n.matches(selector));}
    get elements(){return Object.fromEntries(this.descendants().filter(n=>n.attrs.name).map(n=>[n.attrs.name,n]));}
    reportValidity(){return this.descendants().every(n=>!('required'in n.attrs)||!!n.value);}
    addEventListener(name,fn){this['on'+name]=fn;}
    focus(){document.activeElement=this;}
    scrollIntoView(){}
  }
  const view=new Element('main',{id:'view'});
  document={activeElement:null,querySelector:selector=>view.querySelector(selector),querySelectorAll:selector=>view.querySelectorAll(selector)};
  const state={user:{id:7}},location={hash},calls=[],navigations=[],writes=[],values=new Map(),events={};
  if(saved)values.set('ylPractice:v1:7',JSON.stringify({version:1,selection:{setId:'37',unit:'1',method:'recall',count:'5'},session:clone(saved)}));
  const storage={fail:false,onWrite:null};
  const localStorage={getItem:key=>values.get(key)||null,setItem(key,value){writes.push({key,value});if(storage.fail)throw Error('Fictional storage failure');values.set(key,value);storage.onWrite?.();}};
  const core={state,esc:escape,fmt:String,setView:html=>view.innerHTML=html,toast(){},routeArg:()=>location.hash.split('/')[1]||'',navigate:route=>{navigations.push(route);location.hash='#'+route;},api:async(action,options={})=>{
    calls.push({action,options});
    if(action==='sets')return[{id:37,title:'Synthetic book'}];
    if(action==='study_lessons')return[{kind:'unit',value:1,title:'Synthetic lesson',card_count:sourceCards.length}];
    if(action==='study_lesson_cards')return{cards:clone(sourceCards)};
    if(action==='notebook_notes')return{notes:[],total:0,page:1,pages:1,saved_count:0,max_notes:500};
    if(action==='notebook_save')return{id:901};
    throw Error('Unexpected API '+action);
  }};
  const window={YLCore:core,YLPronunciation:pronunciation,addEventListener:(name,fn)=>events[name]=fn};
  const deterministicMath=Object.create(Math);deterministicMath.random=()=>.999;
  const sandbox={window,document,location,localStorage,sessionStorage:{setItem(){throw Error('No progress write expected');}},requestAnimationFrame:fn=>fn(),setInterval,clearInterval,setTimeout,clearTimeout,Math:deterministicMath,console};
  vm.createContext(sandbox);vm.runInContext(notebook,sandbox,{filename:'learning-notebook.js'});
  // Read/replace handles are test-only; candidate source itself remains uninstrumented.
  const marker='window.YLPractice={view,dispose};';assert.equal(practice.split(marker).length,2);
  vm.runInContext(practice.replace(marker,'window.__practiceTest={get:()=>active,replace:value=>active=value};'+marker),sandbox,{filename:'practice-lab.js'});
  let handoffs=0;const fromCard=window.YLNotebook.fromCard;window.YLNotebook.fromCard=card=>{handoffs++;return fromCard(card);};
  const element=id=>view.querySelector('#'+id),session=()=>window.__practiceTest.get();
  return{window,document,state,location,calls,navigations,writes,values,storage,view,element,session,sessionJSON:()=>JSON.stringify(session()),stored:()=>JSON.parse(values.get('ylPractice:v1:7')).session,get handoffs(){return handoffs;},posts:()=>calls.filter(c=>c.options.method==='POST'),async init(){await window.YLPractice.view();},async begin(){await this.init();element('pl-form').onsubmit({preventDefault(){}});await tick();},async resume(){await this.init();element('pl-resume').onclick();},reveal(){element('pl-reveal').onclick();},answer(text){element('pl-answer').value=text;element('pl-answer-form').onsubmit({preventDefault(){}});},async notebook(){window.YLPractice.dispose();await window.YLNotebook.view();}};
}
async function checked(){const e=environment();await e.begin();e.answer(e.session().cards[0].term);return e;}
(async()=>{
  await scenario('unrevealed prompt has no notebook action, term or IPA',async()=>{const e=environment({sourceCards:[cards[1],cards[0],cards[2]]});await e.begin();check(e.session().cards[0].ipa===cards[1].ipa,'fixture target has existing IPA');check(!e.element('pl-write-sentence'),'no action before answer');check(!e.view.innerHTML.includes(cards[1].term)&&!e.view.innerHTML.includes('əˈweɪk'),'no new early answer or IPA');check(e.calls.every(c=>!c.options.method||c.options.method==='GET'),'only existing reads');});
  await scenario('checked answer opens actual composer without changing the session',async()=>{const e=await checked(),before=e.sessionJSON(),stored=clone(e.stored());check(e.session().cards[0].card_type==='COLLOCATION','new source card type retained');e.element('pl-write-sentence').onclick();check(e.location.hash==='#notebook'&&e.handoffs===1,'one actual handoff');check(e.sessionJSON()===before&&JSON.stringify(e.stored())===JSON.stringify(stored),'queue, pos, scores, retry and feedback exact');check(e.posts().length===0,'no implicit POST');await e.notebook();const form=e.element('note-form');check(form.elements.title.value==='follow up'&&form.elements.body.value.includes(cards[0].example_en)&&form.elements.body.value.includes(cards[0].example_vi),'right card and bilingual reference');check(form.elements.own_sentence.value===''&&form.elements.kind.value==='phrase','empty own sentence and correct category');check(e.document.activeElement===form.elements.own_sentence,'existing composer focuses own sentence');e.element('note-cancel').onclick();check(e.posts().length===0&&!e.element('note-form'),'cancel creates nothing');e.location.hash='#practice/37';await e.resume();check(e.sessionJSON()===before&&e.element('pl-write-sentence'),'resume exact checked feedback');});
  await scenario('reveal at the last initial card does not score, retry or finish',async()=>{const initial=savedSession({pos:2,responses:[{correct:true,source:'typed'},{correct:false,source:'typed'},null]});const e=environment({saved:initial});await e.resume();e.reveal();const before=e.sessionJSON();e.element('pl-write-sentence').onclick();check(e.sessionJSON()===before&&e.stored().responses[2]===null&&!e.stored().retryAdded&&e.stored().pos===2,'reveal stays unscored and same position');e.location.hash='#practice/37';await e.resume();check(e.sessionJSON()===before&&e.element('pl-self-no'),'resume pending self-evaluation, no finish');check(e.handoffs===1&&e.posts().length===0,'one handoff, no write');});
  await scenario('retry card uses that card, leaves retry result and old-session type intact',async()=>{const initial=savedSession({queue:[...cards.map((_,index)=>({index,mode:'recall',repeat:false})),{index:1,mode:'recall',repeat:true}],pos:3,retryAdded:true,responses:[{correct:true,source:'typed'},{correct:false,source:'typed'},{correct:true,source:'typed'}]});delete initial.cards[1].card_type;const e=environment({saved:initial});await e.resume();e.reveal();const before=e.sessionJSON();e.element('pl-write-sentence').onclick();check(e.sessionJSON()===before&&e.stored().retryResults[1]===null&&!('card_type'in e.stored().cards[1]),'legacy source and unscored retry stay exact');await e.notebook();check(e.element('note-form').elements.title.value==='awake'&&e.element('note-form').elements.kind.value==='other','correct retry target and explicit conservative other');check(e.posts().length===0,'no SRS or note creation');});
  await scenario('missing type from a fresh API result is conservative other',async()=>{const source=clone(cards);delete source[0].card_type;const e=environment({sourceCards:source});await e.begin();check(e.session().cards[0].card_type==='OTHER','projection uses explicit other');e.reveal();e.element('pl-write-sentence').onclick();await e.notebook();check(e.element('note-form').elements.kind.value==='other','notebook does not guess vocabulary');});
  await scenario('grammar type survives the practice projection into the existing composer',async()=>{const e=environment({sourceCards:[cards[2],cards[0],cards[1]]});await e.begin();e.reveal();e.element('pl-write-sentence').onclick();await e.notebook();check(e.element('note-form').elements.title.value==='unless'&&e.element('note-form').elements.kind.value==='grammar','correct source card genre, no vocabulary guess');});
  await scenario('storage failure stays in feedback and can be retried',async()=>{const e=await checked(),before=e.sessionJSON(),button=e.element('pl-write-sentence');e.storage.fail=true;button.onclick();check(e.location.hash==='#practice/37'&&e.handoffs===0&&!button.disabled,'failed save stays and reenables');check(e.sessionJSON()===before&&e.element('pl-notebook-note').textContent.includes('chưa chuyển'),'honest message, session intact');e.storage.fail=false;button.onclick();check(e.handoffs===1&&e.location.hash==='#notebook','explicit retry succeeds');});
  await scenario('missing, false and throwing notebook handoff preserve usable feedback',async()=>{for(const failure of ['missing','false','throw']){const e=await checked(),before=e.sessionJSON(),button=e.element('pl-write-sentence');if(failure==='missing')delete e.window.YLNotebook;else e.window.YLNotebook.fromCard=()=>{if(failure==='throw')throw Error('Fictional unavailable module');return false;};button.onclick();check(!button.disabled&&e.location.hash==='#practice/37','unavailable handoff not stuck '+failure);check(e.sessionJSON()===before&&e.posts().length===0&&e.element('pl-notebook-note').textContent.includes('Chưa mở'),'feedback and score intact '+failure);}});
  await scenario('changed owner, exact sibling route, logout and disposal reject captured buttons',async()=>{for(const change of ['owner','sibling','dashboard','logout','dispose']){const e=await checked(),button=e.element('pl-write-sentence'),writes=e.writes.length;if(change==='owner')e.state.user={id:8};if(change==='sibling')e.location.hash='#practice/36';if(change==='dashboard')e.location.hash='#dashboard';if(change==='logout')e.state.user=null;if(change==='dispose')e.window.YLPractice.dispose();button.onclick();check(e.handoffs===0&&e.writes.length===writes&&e.posts().length===0,'stale '+change+' cannot persist or hand off');}});
  await scenario('same-route reentry rejects previous view before its async response',async()=>{const e=await checked(),button=e.element('pl-write-sentence');const loading=e.window.YLPractice.view();button.onclick();check(e.handoffs===0,'entry generation rejects previous view');await loading;});
  await scenario('position, feedback, task, card and session identity reject stale closures',async()=>{for(const change of ['position','feedback','task','card','session']){const e=await checked(),button=e.element('pl-write-sentence'),s=e.session(),writes=e.writes.length;if(change==='position')s.pos++;if(change==='feedback')s.feedback={...s.feedback};if(change==='task')s.queue[s.pos]={...s.queue[s.pos]};if(change==='card')s.cards[s.queue[s.pos].index]={...s.cards[s.queue[s.pos].index]};if(change==='session')e.window.__practiceTest.replace({...s});button.onclick();check(e.handoffs===0&&e.writes.length===writes,'reject replaced '+change);}});
  await scenario('repainted feedback and disconnected or replaced DOM nodes reject old buttons',async()=>{const e=environment();await e.begin();e.answer('a different answer');const old=e.element('pl-write-sentence');e.element('pl-synonym').onclick();const current=e.element('pl-write-sentence');check(old!==current&&!old.isConnected,'actual feedback repaint replaces node');old.onclick();check(e.handoffs===0,'replaced button rejected');current.onclick();check(e.handoffs===1,'current replacement button works');const f=await checked(),button=f.element('pl-write-sentence');button.isConnected=false;button.onclick();check(f.handoffs===0,'disconnected node rejected');});
  await scenario('owner or route changed during persistence is rechecked before handoff',async()=>{for(const change of ['owner','route']){const e=await checked();e.storage.onWrite=()=>{if(change==='owner')e.state.user={id:8};else e.location.hash='#practice/36';};e.element('pl-write-sentence').onclick();check(e.handoffs===0&&e.posts().length===0,'post-persist '+change+' guard');}});
  await scenario('captured double click opens one draft and performs one persistence attempt',async()=>{const e=await checked(),button=e.element('pl-write-sentence'),writes=e.writes.length;button.onclick();button.onclick();check(e.handoffs===1&&e.writes.length===writes+1&&button.disabled,'one-use connector');check(e.posts().length===0&&e.calls.every(c=>['sets','study_lessons','study_lesson_cards'].includes(c.action)),'opening uses no new API');const f=await checked(),sameRoute=f.element('pl-write-sentence');let accepted=0;f.window.YLNotebook.fromCard=()=>{accepted++;return true;};sameRoute.onclick();sameRoute.onclick();check(accepted===1,'once-only guard also holds before a handoff module changes route');});
  await scenario('learner text remains literal through actual practice-to-notebook integration',async()=>{const attack='</textarea><img src=x onerror="bad()"><script>bad()</script> & emoji😀';const source=clone(cards);Object.assign(source[0],{term:attack,definition:attack,example_en:attack,example_vi:attack});const e=environment({sourceCards:source});await e.begin();e.reveal();check(!e.view.querySelector('img')&&!e.view.querySelector('script'),'practice feedback does not inject');e.element('pl-write-sentence').onclick();await e.notebook();const form=e.element('note-form');check(form.elements.title.value===attack&&form.elements.body.value.includes(attack),'literal title and reference preserved');check(!e.view.querySelector('img')&&!e.view.querySelector('script')&&e.posts().length===0,'composer does not inject or save');});
  await scenario('explicit Save after the connector is the only note write',async()=>{const e=await checked();e.element('pl-write-sentence').onclick();await e.notebook();check(e.posts().length===0,'no write before save');const form=e.element('note-form');form.elements.own_sentence.value='I will follow up on my application tomorrow.';await form.onsubmit({preventDefault(){}});check(e.posts().length===1&&e.posts()[0].action==='notebook_save'&&e.posts()[0].options.data.own_sentence===form.elements.own_sentence.value,'intentional save only');check(e.calls.every(c=>!c.options.method||c.options.method==='GET'||c.action==='notebook_save'),'no grade, SRS or progress write');});
  console.log(`PASS: ${scenarios} actual-module scenarios / ${assertions} behavior assertions.`);
})().catch(error=>{console.error(error);process.exitCode=1;});
