<?php
declare(strict_types=1);
$root=dirname(__DIR__);
$required=['index.php','api.php','setup.php','config.php','config.example.php','assets/app.css','assets/tools.css','assets/app.js','database/schema.sql','database/seed.sql','database/migrations/001_auth_login_throttle.sql','database/migrations/002_mistake_book.sql','database/migrations/003_learning_content_types.sql','database/migrations/004_mistake_book_v2.sql','database/migrations/005_personalized_learning_toeic.sql','database/migrations/006_taxonomies_and_toeic_seed.sql','database/migrations/007_toeic_part1_7_starter_and_connected_speech.sql','database/migrations/008_sentence_pattern_library.sql','database/migrations/011_adaptive_learning_schema.sql','database/seeds/011_global_learning_library.sql','database/seeds/012_toeic_adaptive_expansion.sql','database/seeds/013_aptis_adaptive_expansion.sql','database/seeds/014_connected_speech_expansion.sql','docs/DATA_MANIFEST.md','docs/ARCHITECTURE.md','docs/DATABASE_ERD.md','docs/DEFENSE_QA.md','templates/learning-content-import-template.csv','templates/sentence-pattern-import-template.csv','templates/sentence_patterns_v2_193.csv','README.md','DEPLOY_HELIOHOST.md','DATABASE_MIGRATION_GUIDE.md','LEARNING_SYSTEM.md','IMPORT_FORMAT.md','SECURITY.md','TEST_REPORT.md'];
$fail=[];
foreach($required as $f)if(!is_file($root.'/'.$f))$fail[]="Missing $f";
$html=file_get_contents($root.'/index.php');
preg_match_all('/(?:src|href)="([^"?#]+)[^\"]*"/',$html,$m);
foreach(array_unique($m[1]) as $ref){if(str_starts_with($ref,'http:')||str_starts_with($ref,'https:')||str_starts_with($ref,'#')||str_starts_with($ref,'mailto:')||str_starts_with($ref,'data:'))continue;if(str_contains($ref,'<?=')||str_contains($ref,'<?php')||str_starts_with($ref,'<'))continue;$path=$root.'/'.ltrim($ref,'/');if(!is_file($path)&&!is_dir($path))$fail[]="Broken local asset: $ref";}
if(is_file($root.'/config.local.php'))$fail[]='config.local.php must not ship in production ZIP';
$app=file_get_contents($root.'/assets/app.js');
foreach(['async function startDailySession','async function mistakesView'] as $fn)if(!str_contains($app,$fn))$fail[]='Missing critical frontend implementation: '.$fn;
foreach(["route==='mistakes'","route==='patterns'","startDailySession('full')","startDailySession('quick')","sentence_pattern_create","sentence_pattern_import"] as $wire)if(!str_contains($app,$wire))$fail[]='Missing critical frontend route/action wiring: '.$wire;
$scanExt=['php','js','json','md','sql','txt','yml','yaml','htaccess'];
$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));
foreach($it as $file){if(!$file->isFile())continue;$name=$file->getFilename();$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));if($name!=='.htaccess'&&!in_array($ext,$scanExt,true))continue;$content=@file_get_contents($file->getPathname());if($content===false)continue;if(preg_match('/sk-or-v1-[A-Za-z0-9_-]{20,}/',$content))$fail[]='Potential OpenRouter secret: '.$file->getPathname();if(!str_contains($file->getPathname(),'/tests/')&&preg_match_all('/\$2[ayb]\$\d{2}\$[.\/A-Za-z0-9]{53}/',$content,$hashes)){foreach($hashes[0] as $hash){if($hash!=='$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.')$fail[]='Hard-coded bcrypt credential: '.$file->getPathname();}}if(preg_match('/(?:DB_PASS|password)\s*[=:>]\s*[\"\'][^\"\']{8,}[\"\']/i',$content) && !str_contains($file->getPathname(),'tests/')){/* heuristic only; config examples/docs can mention placeholders */}}
if($fail){foreach(array_unique($fail) as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "STATIC AUDIT OK\n";
